server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bole?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 115118
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 47.100.170.169
    database: 0
    port: 6379
    password: 115118
  cache:
    cache-names: menus_cache

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
