server:
  port: 8082

spring:
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    password: MORCWFYULHUZJMOT
    username: dadaglobal@163.com
    properties:
      mail:
        stmp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: ture
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
  redis:
    host: 47.100.170.169
    port: 6379
    password: 115118
    database: 0